# Highlands btop palette

theme_background=false
theme[main_bg]=""
theme[main_fg]="#f2e9cd"
theme[title]="#4e8c6d"
theme[hi_fg]="#e4faa9"
theme[selected_bg]="#373737"
theme[selected_fg]="#f5efda"
theme[inactive_fg]="#67655f"
theme[graph_text]="#f4ecd5"
theme[meter_bg]="#373737"
theme[proc_misc]="#c6a45e"

theme[cpu_box]="#4e8c6d"
theme[mem_box]="#afcb8d"
theme[net_box]="#abeaa5"
theme[proc_box]="#c6a45e"
theme[div_line]="#67655f"

theme[temp_start]="#abeaa5"
theme[temp_mid]="#e4faa9"
theme[temp_end]="#b5aa66"

theme[cpu_start]="#4e8c6d"
theme[cpu_mid]="#abeaa5"
theme[cpu_end]="#b7ffaf"

theme[free_start]="#abeaa5"
theme[free_mid]="#afcb8d"
theme[free_end]="#c0e593"

theme[cached_start]="#67655f"
theme[cached_mid]="#4e8c6d"
theme[cached_end]="#abeaa5"

theme[available_start]="#c6a45e"
theme[available_mid]="#afcb8d"
theme[available_end]="#e4faa9"

theme[used_start]="#e4faa9"
theme[used_mid]="#aca477"
theme[used_end]="#9d945f"

theme[download_start]="#4e8c6d"
theme[download_mid]="#abeaa5"
theme[download_end]="#b7ffaf"

theme[upload_start]="#c6a45e"
theme[upload_mid]="#e4b85b"
theme[upload_end]="#e4faa9"

theme[process_start]="#afcb8d"
theme[process_mid]="#4e8c6d"
theme[process_end]="#c6a45e"

theme[gradient_color_0]="#212121"
theme[gradient_color_1]="#373737"
theme[gradient_color_2]="#67655f"
theme[gradient_color_3]="#4e8c6d"
theme[gradient_color_4]="#abeaa5"
theme[gradient_color_5]="#afcb8d"
theme[gradient_color_6]="#e4faa9"
theme[gradient_color_7]="#f5efda"
